### ISSUE TITLE
Use &amp; rather than & in all HTML text

### ISSUE THREAD

**Issue by MarkPThomas** [rpp29-fec-gouda/atelier#39]
https://github.com/rpp29-fec-gouda/atelier/blob/ac03a66325fc598fb8f3af72d6237e56eb1d4b1b/client/src/components/ratingsReviews/RatingsAndReviews.jsx#L78

This should be corrected for any reserved character anywhere it appears as rendered text in the HTML. Characters to look out for:
`&amp;` = &
`&lt;` = <
`&gt;` = >

**Comment by aleksandar-cakic** [comment]
@MarkPThomas Updated in PR#41. Also added the character references to my notes for future use. 

Thanks!
